
#查询间隔 单位:s
searchInterval: 60

#Store Code
storeNumber: "R824"

#手机型号, 通过访问官网,选择机型 可在uri中得到 比如 MLE93CH/A (iphone 13 512GB 粉色)
modals: ["MU673LL/A"]


#推送url 需要下载Bark app 在ios可得到 https://api.day.app/xxx
notifyUrl: ["https://api.day.app/iX4i5VT9xDeQGrPkMXmghL"]

#消息是否根据取货地点合并通知
notifyMergedByStore: false